### ISSUE TITLE
Build status should show why it failed when the build pod runs out of ephemeral disk space

### ISSUE THREAD

**Issue by davewalter** [buildpacks-community/kpack#1255]
#### Details

When the build pod errors due to a full ephemeral storage disk, the Build's Ready status condition is set to false without a useful reason or message that indicates why.

```yaml
status:
  conditions:
  - lastTransitionTime: "2023-07-11T23:37:02Z"
    status: "False"
    type: Succeeded
```

Inspecting the build pod's status, the `Ready` status condition simply indicates that the pod has failed:

```yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-07-11T23:34:51Z"
    reason: PodFailed
    status: "False"
    type: Ready
```

The `status.initContainerStatuses[{name: "build"}].state` shows that the container has terminated with an exit code of `2` and a reason of `Error`:

```yaml
status:
  initContainerStatuses:
  - name: build
    ...
    ready: false
    state:
      terminated:
        containerID: ...
        exitCode: 2
        finishedAt: "2023-07-11T23:37:01Z"
        reason: Error
        startedAt: "2023-07-11T23:34:56Z"
```

The only useful status from the build pod is the `status.message` field, which states `"Pod ephemeral local storage usage exceeds the total limit of containers"`.

It would be helpful to be able to see the useful error message reflected in the `Build` (and `Image`) succeeded status conditions in the human-readable `message` field. It would also be nice to see the machine-readable `reason` field copied from the build pod's ready status condition into the succeeded conditions for both resources.
