### ISSUE TITLE
Build phase does not load git ssh secret

### ISSUE THREAD

**Issue by wdonne** [buildpacks-community/kpack#1583]
Only the prepare and completion phases load the git ssh secret. The build phase does not. It is also not possible to inject the private ssh key through an environment variable in the `build` field of the `Image` resource because the `valueFrom` field is not supported. As a consequence, it is not possible to use private git repositories in the build phase. Languages like Dart and Go can use git repositories for their dependencies.

**Comment by tomkennedy513** [comment]
For this case you will want to use the git buildpack (https://github.com/paketo-buildpacks/git) to mount git creds needed for builds as a service binding. Kpack purposefully does not mount any credentials to the build to remain compliant with SLSA Level 3 hardened builds so you need to use bindings for this.

**Comment by wdonne** [comment]
That buildpack will only work if there is a `.git` directory in the project source. I don't see how this will help when, for example, a Flutter project refers to another package using a git URL. If the `Image` resource would support volumes, an SSH private key could be injected at the default location in the filesystem.

**Comment by tomkennedy513** [comment]
That buildpack will also participate if there is a git config service binding which sounds like the use case you have

**Comment by wdonne** [comment]
In fact, this Paketo buildpack is not needed. kpack supports service bindings. In the `Image` resource you can add the `services` field to the `build` field. A service can also be just a secret. It would look like this:
```
  build:
    services:
      - name: my-git-secret
        kind: Secret
        apiVersion: v1
```
The secret would be like this:
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kpack.io/git: git@bitbucket.org
  name: my-git-secret
  namespace: buildpacks
type: service.binding/ssh-auth
stringData:
  id_rsa: XXXXXXX
  type: ssh-auth
```
Then, you can add the file `/etc/ssh/ssh_config` to your build image with something like this:
```
Host *
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
   IdentityFile /platform/bindings/my-git-secret/id_rsa
```
