### ISSUE TITLE
Update to support 0.10 of the Buildpack API

### ISSUE THREAD

**Issue by jwhitcraft** [buildpacks-community/kpack#1730]
Hello,

I recently ran into a problem when trying to use the heroku based buildpacks where one of their buildpacks didn't define a `stacks` section in the buildpack.toml file.  Kpack says that it's not supported, 

`message: "validating buildpack heroku procfile@3.1.2: stack heroku-24 is not supported"`

In talking with that team, it seems that kpack neesd to be updated to support 0.10 where `stacks` are optional/deprecated.

This came out of this discussion here: https://github.com/heroku/buildpacks-procfile/issues/243

For reference here is when the pack cli fixed it: https://github.com/buildpacks/pack/issues/2047

<details><summary>Yaml</summary>

```
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: heroku-242
spec:
  order:
    - group:
        - id: heroku/nodejs
        - id: heroku/procfile
  serviceAccountRef:
    name: kpack
    namespace: kpack
  stack:
    kind: ClusterStack
    name: heroku-24
  store:
    kind: ClusterStore
    name: heroku-24
  tag: 1231232132.dkr.ecr.us-east-2.amazonaws.com/heroku-24-builder
  additionalLabels:
    io.buildpacks.base.distro.name: "ubuntu"
    io.buildpacks.base.distro.version: "24.04"

---

apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: heroku-24
spec:
  buildImage:
    image: public.ecr.aws/heroku/builder:24
  id: heroku-24
  runImage:
    image: public.ecr.aws/heroku/heroku:24

---

apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: heroku-24
spec:
  sources:
    - image: heroku/buildpack-nodejs:3.2.15
    - image: heroku/buildpack-procfile:3.1.2
```

</details>
