### ISSUE TITLE
❗ Issue: Unable to Pull paketo-buildpacks/java from Docker Hub after Migration

### ISSUE THREAD

**Issue by ponsurya1805** [buildpacks-community/kpack#1877]
Description:

After Docker Hub’s recent migration and access control changes, we are encountering pull errors when attempting to fetch the paketo-buildpacks/java buildpack using a Kpack ClusterStore.

Error:

`GET https://index.docker.io/v2/paketo-buildpacks/java/manifests/18.0.0:
UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:paketo-buildpacks/java Type:repository]]`

Config: 

```
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: test2
spec:
  sources:
    - image: docker.io/paketo-buildpacks/java:18.0.0
Status:
conditions:
  - lastTransitionTime: "2025-06-20T08:25:55Z"
    message: 'GET https://index.docker.io/v2/paketo-buildpacks/java/manifests/18.0.0:
      UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:paketo-buildpacks/java
      Type:repository]]'
    status: "False"
    type: Ready
```

Expected Behavior:

The buildpack image should be pulled and added to the ClusterStore without authentication failure.

Request for Help:

Could you please help us with a fix 

Thanks in advance for your support!
