### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by PungYoung** [buildpacks-community/kpack#1882]
```yaml
kubectl apply -f - << EOF
apiVersion: kpack.io/v1alpha2
kind: Build
metadata:
  name: sample
spec:
  tags:
  - 192.168.0.146/sample/image
  serviceAccountName: glb-sa
  builder:
    image: docker.m.daocloud.io/paketobuildpacks/builder-jammy-base:0.4.429
  runImage: 
    image: docker.m.daocloud.io/paketobuildpacks/builder-jammy-base:0.4.429
  source:
    git:
      url: https://gitee.com/pungyoung/glb.git # bd102d7f091503429b956cc8cd3cb55a
      revision: master
EOF
```
```sh
kubectl logs -n default sample-build-pod -c prepare -f
```
out
```
Loading registry credentials from service account secrets
No registry credentials were loaded from service account secrets
Loading cluster credential helpers
Loading secrets for "https://gitee.com" from secret "gitee"
Cloning "https://gitee.com/pungyoung/glb.git" @ "master"...
unable to fetch references for repository: error decoding upload-pack response: invalid pkt-len found
```
