### ISSUE TITLE
[Feature] Pull archived source from remote registry location

### ISSUE THREAD

**Issue by mgibson1121** [buildpacks-community/kpack#55]
As a user of build-service system 
I want to reference source code that lives in a blobstore when creating an image type 
So that build service system can execute builds against it

**Given** I have a file stored in a blobstore that contains source code in at `gcr.io/myapp/myimage@sha256:2ab3da...`
**And** I configure my image type to look like this

```
apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: sample-image
spec:
  serviceAccount: service-account 
  builderRef: sample-builder
  image: gcr.io/project-name/app
  cacheSize: "1.5Gi"
  failedBuildHistoryLimit: 5
  successBuildHistoryLimit: 5
  source
     registry:
         image: gcr.io/myapp/myimage@sha256:2ab3da...
         imagePullSecrets: 
         - my-secret
 ```

**When** I run `kubectl image apply` and reference this image type
**Then** build service system will execute builds utilizing the registry creds associated with the image config to pull the image `gcr.io/myapp/myimage@sha256:2ab3da...`

**Notes**

* Attempt to use the full contents of the image regardless of the number of layers eg. by adding the layers to the builder
