### ISSUE TITLE
RFC: Image cache read "fallback mechanism" + ability to push multiple cache tags

### ISSUE THREAD

**Issue by fgrehm** [buildpacks-community/kpack#966]
Hey folks!

Would you be open to a feature that would allow us to make use of different image cache tags for reading / writing? For example:

```yaml
apiVersion: kpack.io/v1alpha2
kind: Build
metadata:
  name: sample
spec:
  tags:
  - "sample/image:<short-sha>"
  - "sample/image:<branch-name>"
  cache:
    registry:
      read:
      # First image found is used, go from more specific to more "generic"
      - "sample/image-cache:<short-sha>"
      - "sample/image-cache:<branch-name>"
      - "sample/image-cache:main"
      - "sample/image-cache:master"
      # Pushes an image with both tags
      write:
      - "sample/image-cache:<short-sha>"
      - "sample/image-cache:<branch-name>"
  # ...
```

We currently have a custom build process & script that manually execute `lifecycle` CLI steps which yields a very nice "cache experience", reducing build times quite a lot. Can try pulling up some numbers but this is great for situations like building a branch with dependency updates multiple times for deployments to staging environments.

**NOTE**: In case you are wondering: "`sample/image-cache` registry will grow a lot right?". Yes, but our registries have a "GC mechanism" that cleans up images that haven't been pulled after X time, with the exception of some specific tags (like `master` / `main` / etc). In other words, storage is not a big deal for us :sweat_smile: 

#### Example scenario

_Added on 2022-06-30_

For brevity, lets assume there's already images built for the main branch of `app`, meaning we have `app-cache:main` available for use. Time passes and devs decide / need to upgrade project dependencies (ex: `bundle update`), so they cut a `upgrade-deps` branch with the changes and deploy to a staging environment. Build resource cache will look like this:

```yaml
      read:
      - "app-cache:abcdefg" # MISS
      - "app-cache:upgrade-deps" # MISS
      - "app-cache:main" # HIT
      write:
      - "sample/image-cache:abcdefg"
      - "sample/image-cache:upgrade-deps"
```

The first image build for that deployment might be slower than usual depending on the amount of deps to upgrade, but they won't be _terribly_ slow because the cache read will pull `<img>-cache:main` and reuse _some_ of the dependencies already available. Lets just say it's a Ruby app and that it's upgrading a large dependency that requires compilation due to native extensions (I've seen cases which a single dep might add like 3-4minutes to a build).

Same day after deploying, a QA person jumps in to do a smoke test and finds a bug. The dev then fixes the code and redeploys for another round of QA. Build resource cache will now look like this:

```yaml
      read:
      - "app-cache:0123456" # MISS
      - "app-cache:upgrade-deps" # HIT
      - "app-cache:main"
      write:
      - "app-cache:0123456"
      - "app-cache:upgrade-deps"
```

This time, because only the application code changed, build will be a lot faster and devs can "almost instantly" issue a deployment to check if the bug really got fixed in a prod like environment before asking QA to do more exploratory testing. This back and forth can go a few times, meaning lots of builds will need to happen and those will be a lot faster than if we were using only a single cache for the main branch.

Shaving those minutes off from builds can speed up a lot our feedback loop and troubleshooting sessions. As you probably know, there are many times when things only work on our machines and only break as it gets closer to production :sweat_smile:
